// <auto-generated />
using System;
using BrewLab.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BrewLab.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260628053124_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BrewLab.Models.Entities.BrewMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BrewMethods");
                });

            modelBuilder.Entity("BrewLab.Models.Entities.BrewParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrewMethodId")
                        .HasColumnType("uuid");

                    b.Property<int>("DataType")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BrewMethodId");

                    b.ToTable("BrewParameters");
                });

            modelBuilder.Entity("BrewLab.Models.Entities.Coffee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origin")
                        .HasColumnType("text");

                    b.Property<int?>("Process")
                        .HasColumnType("integer");

                    b.Property<int>("Roast")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RoastDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TastingNotes")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Coffees");
                });

            modelBuilder.Entity("BrewLab.Models.Entities.Experiment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Acidity")
                        .HasColumnType("integer");

                    b.Property<int?>("Aftertaste")
                        .HasColumnType("integer");

                    b.Property<int?>("Aroma")
                        .HasColumnType("integer");

                    b.Property<int?>("Bitterness")
                        .HasColumnType("integer");

                    b.Property<int?>("Body")
                        .HasColumnType("integer");

                    b.Property<Guid>("BrewMethodId")
                        .HasColumnType("uuid");

                    b.Property<int>("BrewTime")
                        .HasColumnType("integer");

                    b.Property<Guid>("CoffeeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CoffeeWeight")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Extraction")
                        .HasColumnType("integer");

                    b.Property<string>("GrindSetting")
                        .HasColumnType("text");

                    b.Property<int>("Overall")
                        .HasColumnType("integer");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<int?>("Sweetness")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("WaterTemperature")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WaterWeight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BrewMethodId");

                    b.HasIndex("CoffeeId");

                    b.HasIndex("UserId");

                    b.ToTable("Experiments");
                });

            modelBuilder.Entity("BrewLab.Models.Entities.ExperimentParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrewParameterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExperimentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BrewParameterId");

                    b.HasIndex("ExperimentId");

                    b.ToTable("ExperimentParameters");
                });

            modelBuilder.Entity("BrewLab.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BrewLab.Models.Entities.BrewParameter", b =>
                {
                    b.HasOne("BrewLab.Models.Entities.BrewMethod", "BrewMethod")
                        .WithMany("BrewParameters")
                        .HasForeignKey("BrewMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrewMethod");
                });

            modelBuilder.Entity("BrewLab.Models.Entities.Coffee", b =>
                {
                    b.HasOne("BrewLab.Models.Entities.User", "User")
                        .WithMany("Coffees")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BrewLab.Models.Entities.Experiment", b =>
                {
                    b.HasOne("BrewLab.Models.Entities.BrewMethod", "BrewMethod")
                        .WithMany("Experiments")
                        .HasForeignKey("BrewMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrewLab.Models.Entities.Coffee", "Coffee")
                        .WithMany("Experiments")
                        .HasForeignKey("CoffeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrewLab.Models.Entities.User", "User")
                        .WithMany("Experiments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrewMethod");

                    b.Navigation("Coffee");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BrewLab.Models.Entities.ExperimentParameter", b =>
                {
                    b.HasOne("BrewLab.Models.Entities.BrewParameter", "BrewParameter")
                        .WithMany("ExperimentParameters")
                        .HasForeignKey("BrewParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrewLab.Models.Entities.Experiment", "Experiment")
                        .WithMany("Parameters")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrewParameter");

                    b.Navigation("Experiment");
                });

            modelBuilder.Entity("BrewLab.Models.Entities.BrewMethod", b =>
                {
                    b.Navigation("BrewParameters");

                    b.Navigation("Experiments");
                });

            modelBuilder.Entity("BrewLab.Models.Entities.BrewParameter", b =>
                {
                    b.Navigation("ExperimentParameters");
                });

            modelBuilder.Entity("BrewLab.Models.Entities.Coffee", b =>
                {
                    b.Navigation("Experiments");
                });

            modelBuilder.Entity("BrewLab.Models.Entities.Experiment", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("BrewLab.Models.Entities.User", b =>
                {
                    b.Navigation("Coffees");

                    b.Navigation("Experiments");
                });
#pragma warning restore 612, 618
        }
    }
}
